Support import disk functionallity
distributed-technologies/mukube-terraform pull request #5
Opened 2021-09-24 06:34 UTC by jacobcrawford

2021-09-24 10:09 UTC, skovbakke requested changes
We should not use the absolute path of files.

2021-09-24 10:09 UTC, skovbakke commented on vm_module/main.tf
> +    iso = var.os_format == "iso" ? var.os : "/var/lib/vz/template/iso/ubuntu-18.04.5-desktop-amd64.iso" ## We need to specify iso
Why do we default to ubuntu desktop?

2021-09-27 05:18 UTC, jacobcrawford commented on vm_module/main.tf
> +    iso = var.os_format == "iso" ? var.os : "/var/lib/vz/template/iso/ubuntu-18.04.5-desktop-amd64.iso" ## We need to specify iso
To use the provider one of "clone" and "iso" needs to be specified. I just put Ubuntu to get it to work, but we need a different solution. Though it has to be a file that we know will not be deleted.

2021-09-27 07:25 UTC, jacobcrawford commented on variables.tf
> +  description = "The absolute path to the os folder in the Proxmox."
Unfortunately, this cannot be done for wic image files.

2021-09-27 07:31 UTC, jacobcrawford commented on vm_module/main.tf
> +    iso = var.os_format == "iso" ? var.os : "/var/lib/vz/template/iso/ubuntu-18.04.5-desktop-amd64.iso" ## We need to specify iso
I have downloaded an Alpine image instead.

2021-09-27 10:57 UTC, skovbakke requested changes
looks good, only a small suggestion left.

2021-09-27 10:57 UTC, skovbakke commented on vm_module/main.tf
> +      "chmod +x /tmp/script.sh",
How about making the script executable?  Currently the script access mode is `664`. or does the mode somehow change after it is transferred to the remote machine?

2021-09-27 10:57 UTC, skovbakke commented on vm_module/main.tf
> +    iso = var.os_format == "iso" ? var.os : "/var/lib/vz/template/iso/ubuntu-18.04.5-desktop-amd64.iso" ## We need to specify iso
That is probably better.

2021-09-27 11:33 UTC, klausenbusk commented on script.sh
> +VM_ID=$1
Please add a shebang:
```suggestion
#!/bin/bash
VM_ID=$1
```

2021-09-27 11:33 UTC, klausenbusk commented on script.sh
> +qm start $VM_ID
Fix [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086):
```suggestion
qm stop "$VM_ID"
qm importdisk "$VM_ID" "$IMAGE_PATH $STORAGE_POOL"
qm set "$VM_ID" --scsi0 "$STORAGE_POOL:vm-$VM_ID-disk-$DISK_COUNT"
qm set "$VM_ID" --boot order=scsi0
qm start "$VM_ID"
```

2021-09-27 12:02 UTC, jacobcrawford commented on vm_module/main.tf
> +      "chmod +x /tmp/script.sh",
As the script is only supposed to be executable on the remote machine I think it is best practice to leave it non-executable in the version control. Maybe we should restrict it further in the version control.

2021-09-27 13:01 UTC, skovbakke commented on vm_module/main.tf
> +      "chmod +x /tmp/script.sh",
That is fine

2021-09-27 13:08 UTC, merged